
from flask import render_template, request, jsonify


# Permet de récupérer tous les commentaires pour un media
@api.route('/arte', methods=['POST'])
def getLicenceM6():

	error = ""

	data_output = {"service_version_info":{"license_sdk_version":"18.1.2","license_service_version":"DRMtoday"},"supported_tracks":[{"type":"SD","key_id":"RH1/SvCfPkiV5JYOU22ZWg=="},{"type":"SD","key_id":"k0vHxqApPVueJhpzJHd1Aw=="},{"type":"HD","key_id":"Qz/7pnCWPnCFeFmp3/S+BA=="},{"type":"AUDIO","key_id":"MwzwlmZlPtm2IaHMLv9ReA=="},{"type":"HD","key_id":"bhCH7zD3NmG+tfqL16SIUg=="},{"type":"AUDIO","key_id":"kdlGe9eVMYugfEhn/0OB5w=="}],"message_type":"LICENSE_REQUEST","status":"OK","license":"CAIStwYKPgoQRl79npEeIxVv2BF60UJKKxImChCQb8MTgABBXKrqaqide+SoEAEyEDpWYnQ1/KD+H/r5o7xPE/AgASgAEh0IARABGAAgACgAOABCAEgAUABYAGABcAB4AYABABpWEhDqoH/h8F3fvSVws+r87UEAGkAoJCcoUd78K3yKKsPD8PUibYQFThvBmD/+tkTwHZceJ6de5Rl5T2a2QJYIeQZ44tOz5wfPXRaqXriKW8dm/V4nIAEaZgoQRH1/SvCfPkiV5JYOU22ZWhIQfhYKlQaXGfmk7izMUmBpkhoQ9DO7FGCHTInda12qWPMxCiACKAEyCAgAECoYACAAOggIABAqGAAgAEISChBrYzE2AAAAAKynB4WgAAAIYgJTRBpmChCTS8fGoCk9W54mGnMkd3UDEhATYzQtFSulV3ZoGhjZZe2GGhAAxRGauhFtMmhFE1lSJ613IAIoATIICAAQKhgAIAA6CAgAECoYACAAQhIKEGtjMTYAAAAArKcHhaAAAAhiAlNEGmYKEEM/+6Zwlj5whXhZqd/0vgQSEA9FN3HMPn66EZg6f9Hxq2IaEHsDNY3Q2arRjz/HgzQP+IMgAigBMggIABAqGAAgADoICAAQKhgAIABCEgoQa2MxNgAAAACspweFoAAACGICSEQaaQoQMwzwlmZlPtm2IaHMLv9ReBIQmbmlZVh4vn8+4LOdf1DoRhoQxw80YJCJaKH5UROpRMyEaSACKAEyCAgAECoYACAAOggIABAqGAAgAEISChBrYzE2AAAAAKynB4WgAAAIYgVBVURJTxpmChBuEIfvMPc2Yb61+ovXpIhSEhDF+Zj7FhPfqb6FlJPPTWgcGhAm1kjpDLUvi8bHJsJA/Bl2IAIoATIICAAQKhgAIAA6CAgAECoYACAAQhIKEGtjMTYAAAAArKcHhaAAAAhiAkhEGmkKEJHZRnvXlTGLoHxIZ/9DgecSEAL2jSdjufqxPwrnNjLxKqcaEPDqQ7oLPg10oaPvcmK8/aIgAigBMggIABAqGAAgADoICAAQKhgAIABCEgoQa2MxNgAAAACspweFoAAACGIFQVVESU8gpI2urwY4AFACGiBHEg4OkLvlgwTH3gluvbXXBin8OZGnhq3PH+1ROaJJ6CKAAUtkZ1qGwaDtHMpxzmr3nKOieq6ykBr1qmcVGDjBR+tsyyplO9uRVVsDRkVVh0AT6xVI1Zo9n+w6M9mNkN7oJPFjZaqFyilnvaDbVu9QqKVcZtdrbtDdi9XbMgtG8BFBho+mangOlOCBTwTKGlDBrkPXfnYiLa0DnSIwdwG4k7UWOggKBjE4LjEuMkABSvgCAAAAAgAAAXgABQAQrKcHha6hgikAAABjAAAAEAAAAHUAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAC7AAAAEAAAAM0AAAAQAAAA3wAAABAAAAAAAAAAAAAAAQsAAAAQAAABIwAAABAAAAE1AAAAEAAAAUcAAAAQAAAAAAAAAAAAAAELAAAAEAAAAYsAAAAQAAABnQAAABAAAAGvAAAAEAAAAAAAAAAAAAABCwAAABAAAAHzAAAAEAAAAgUAAAAQAAACFwAAABAAAAAAAAAAAAAAAQsAAAAQAAACXgAAABAAAAJwAAAAEAAAAoIAAAAQAAAAAAAAAAAAAAELAAAAEAAAAsYAAAAQAAAC2AAAABAAAALqAAAAEAAAAAAAAAAAAAABCwAAABDn5Q5f7ax39aFVVYbXge/RtYrGKdOm5fkKRV6sbpj7VFgB","platform":"macos"}
	# Si on a pas d'erreur 
	if not error and data_output["url"]:
		d = json_return("",200,data_output)
	else:
		d = json_return(error,400,"")

	return jsonify(d),200

"https://api.arte.tv/api/player/v2/config/fr/LIVE"